### ISSUE TITLE
Crash upon entering world

### ISSUE THREAD

**Issue by Pokechu22** [Pokechu22/WorldDownloader#10]
*[[Originally reported by codahq on the forums]](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285484-world-downloader-mod?comment=2042)*

On some servers, in some circumstances, upon joining the game would immediately crash.  This occurred in both the liteloader version and coremod version.  

Crash report: 

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  SmartCorePlugin (SmartMoving-1.8-16.1.jar)
  PlayerAPIPlugin (PlayerAPI-1.8-1.3.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  ItemPatchingLoader (ItemPhysic Lite 1.1.3 mc1.8.jar)
  CCCDeobfPlugin (unknown)
  RenderPlayerAPIPlugin (RenderPlayerAPI-1.8-1.4.jar)
  DLFMLCorePlugin (DynamicLights-1.8.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  LoadingPlugin (PixelCam-1.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 7/21/15 1:08 AM
Description: WDL mod: exception in onWorldRemoveEntityFromWorld event

java.lang.NullPointerException: WDL mod: exception in onWorldRemoveEntityFromWorld event
	at wdl.WDLHooks.onWorldClientRemoveEntityFromWorld(WDLHooks.java:153)
	at wdl.litemod.LiteModWDL.worldClientRemoveEntityFromWorld(LiteModWDL.java:104)
	at com.mumfrey.liteloader.core.event.EventProxy.$event0000b(EventProxy.java:222)
	at net.minecraft.client.multiplayer.WorldClient.func_73028_b(WorldClient.java)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147238_a(NetHandlerPlayClient.java:588)
	at net.minecraft.network.play.server.S13PacketDestroyEntities.func_148833_a(SourceFile:42)
	at net.minecraft.network.play.server.S13PacketDestroyEntities.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1018)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 966525152 bytes (921 MB) / 1834483712 bytes (1749 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1491 Optifine OptiFine_1.8_HD_U_D5 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1491.jar) 
	UCHIJA	Forge{11.14.3.1491} [Minecraft Forge] (forge-1.8-11.14.3.1491.jar) 
	UCHIJA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHIJA	PlayerAPI{1.3} [Player API] (minecraft.jar) 
	UCHIJA	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHIJA	SmartCore{1.2} [Smart Core] (minecraft.jar) 
	UCHIJA	itemphysic{1.1.2} [ItemPhysic] (minecraft.jar) 
	UCHIJA	SmartMoving{16.1} [Smart Moving] (SmartMoving-1.8-16.1.jar) 
	UCHIJA	DamageIndicatorsMod{3.3.3} [Damage Indicators] ([1.8]DamageIndicatorsMod-3.3.3.jar) 
	UCHIJA	iChunUtil{5.4.0} [iChunUtil] (iChunUtil-5.4.0.jar) 
	UCHIJA	BackTools{5.1.0} [BackTools] (BackTools-5.1.0.jar) 
	UCHIJA	BetterFoliage{1.1.5} [Better Foliage] (BetterFoliage-mc1.8-1.1.5.jar) 
	UCHIJA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.jar) 
	UCHIJA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJA	pearlmod{0.3.0.16} [Pearlmod] (pearlmod-1.8.0-0.3.1.0.jar) 
	UCHIJA	PixelCam{1.2} [PixelCam] (PixelCam-1.2.jar) 
	UCHIJA	Shatter{5.0.0} [Shatter] (Shatter-5.0.0.jar) 
	UCHIJA	SmartRender{2.1} [Smart Render] (SmartRender-1.8-2.1.jar) 
	UCHIJA	Streak{5.0.1} [Streak] (Streak-5.0.1.jar) 
	UCHIJA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
  mods.betterfoliage.loader.impl.BetterFoliageTransformer
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
SmartCorePlugin (SmartMoving-1.8-16.1.jar)
  net.smart.core.SmartCoreTransformer
PlayerAPIPlugin (PlayerAPI-1.8-1.3.jar)
  api.player.forge.PlayerAPITransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
ItemPatchingLoader (ItemPhysic Lite 1.1.3 mc1.8.jar)
  com.creativemd.itemphysic.ItemTransformer
CCCDeobfPlugin (unknown)
  
RenderPlayerAPIPlugin (RenderPlayerAPI-1.8-1.4.jar)
  api.player.forge.RenderPlayerAPITransformer
DLFMLCorePlugin (DynamicLights-1.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
LoadingPlugin (PixelCam-1.2.jar)
  eu.crushedpixel.pixelcam.coremod.CameraTiltingCT
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1046.0' Renderer: 'AMD Radeon R9 200 / HD 7900 Series'
```
(*[source](http://pastebin.com/M4ywdST4)*)

**Comment by Pokechu22** [comment]
Fixed in [1.8c-fix1](https://github.com/Pokechu22/WorldDownloader/releases/tag/1.8c-fix1).

(The exact cause was that an entity was removed before WDL's load event, leading `WDL.worldClient` null when the event occurred.  The fix is to use the `sender` param, which won't be null.)

**Comment by darkarrow** [comment]
This is still happening to me with the version that you have linked in your post.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/9/15 11:15 AM
Description: WDL mod: exception in onWorldClientTick event

java.lang.NullPointerException: WDL mod: exception in onWorldClientTick event
	at wdl.WDL.loadWorld(WDL.java:353)
	at wdl.WDLEvents.onWorldLoad(WDLEvents.java:81)
	at wdl.WDLHooks.onWorldClientTick(WDLHooks.java:34)
	at cen.c(WorldClient.java:107)
	at bsu.r(SourceFile:1839)
	at bsu.as(SourceFile:877)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 172103712 bytes (164 MB) / 254705664 bytes (242 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
