### ISSUE TITLE
Worlds do not save after getting disconnected on 1.14+ versions

### ISSUE THREAD

**Issue by forkiesassds** [Pokechu22/WorldDownloader#176]
If you get disconnected while downloading a world it attempts to save but it does not, and after reconnecting it saves and starts downloading again, but after you start to download new chunks it fails with an NPE error, and stopping downloading causes the game to crash. Happens on both Forge and Baseedit.
Crashlog: https://hasteb.in/ifasutij.yaml

**Comment by Pokechu22** [comment]
Confirmed.  It seems that the 1.14 and 1.15 builds don't detect the disconnect at all, so when you join the server again, it thinks you were already downloading and state is all messed up (things also go really weird if you enter a singleplayer world).  Investigating...

**Comment by Pokechu22** [comment]
Should be fixed now, see commit 42f4548ac8987c1ea025fe24dd9bfd9d44031bb8 for details.  There's still a fair bit of jank with the disconnect-handling code, but it at least seems to work now from my testing.

**Comment by forkiesassds** [comment]
It still gets messed up when you join the server back before it gets saved.

**Comment by Pokechu22** [comment]
Well, that's annoying.  I did notice that the save progress GUI wasn't appearing when I tested the fix, but I didn't check what happened if another world was loaded in that time.

Unfortunately, fixing that is probably going to be much harder (assuming I can't figure out why the GUI isn't showing up); the way WDL handles state is rather fragile and if things end up in an unexpected situation then it can break in weird ways.
