### ISSUE TITLE
Compile Error with gradlew(Win10) gradle(Mint19) setupDecompWorkspace build

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#96]
Pulled code Today
Compile started with gradlew(Win10) gradle(Mint19) setupDecompWorkspace build, from command line
Runs until it reaches here then crashes This happens on Windows 10 and Mint 19

:1.09:sourceMainJava
:1.09:compileJava
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/multiplayer/WorldClient.java:223: error: cannot find symbol
                        if (entityIn.isEntityAlive()) {
                                    ^
  symbol:   method isEntityAlive()
  location: variable entityIn of type Entity
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/multiplayer/WorldClient.java:369: error: cannot find symbol
                                if (!entity2.isDead && entity2.isPassenger(entity1)) {
                                            ^
  symbol:   variable isDead
  location: variable entity2 of type Entity
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/multiplayer/WorldClient.java:376: error: cannot find symbol
                        if (entity1.isDead) {
                                   ^
  symbol:   variable isDead
  location: variable entity1 of type Entity
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/multiplayer/WorldClient.java:376: error: illegal start of type
                        if (entity1.isDead) {
                           ^
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/multiplayer/WorldClient.java:441: error: cannot find symbol
                this.mc.effectRenderer.addEffect(new EntityFirework.StarterFX(this, x, y, z, motionX, motionY, motionZ, this.mc.effectRenderer, compound));
                                                                                                                               ^
  symbol:   variable effectRenderer
  location: variable mc of type Minecraft
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/multiplayer/WorldClient.java:441: error: cannot find symbol
                this.mc.effectRenderer.addEffect(new EntityFirework.StarterFX(this, x, y, z, motionX, motionY, motionZ, this.mc.effectRenderer, compound));
                       ^
  symbol:   variable effectRenderer
  location: variable mc of type Minecraft
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:533: error: cannot find symbol
                                entity.onGround = packetIn.getOnGround();
                                                          ^
  symbol:   method getOnGround()
  location: variable packetIn of type SPacketEntityTeleport
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:639: error: cannot find symbol
                this.netManager.sendPacket(new CPacketPlayer.C06PacketPlayerPosLook(entityplayer.posX, entityplayer.getEntityBoundingBox().minY, entityplayer.posZ, entityplayer.rotationYaw, entityplayer.rotationPitch, false));
                                                                                                                   ^
  symbol:   method getEntityBoundingBox()
  location: variable entityplayer of type EntityPlayer
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:740: error: cannot find symbol
                        this.client.effectRenderer.addEffect(new EntityPickupFX(this.world, entity, entitylivingbase, 0.5F));
                                   ^
  symbol:   variable effectRenderer
  location: variable client of type Minecraft
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:783: error: cannot find symbol
                                this.client.effectRenderer.func_178926_a(entity, EnumParticleTypes.CRIT);
                                           ^
  symbol:   variable effectRenderer
  location: variable client of type Minecraft
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:785: error: cannot find symbol
                                this.client.effectRenderer.func_178926_a(entity, EnumParticleTypes.CRIT_MAGIC);
                                           ^
  symbol:   variable effectRenderer
  location: variable client of type Minecraft
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:1100: error: cannot find symbol
                                tileentity.readFromNBT(packetIn.getNbtCompound());
                                          ^
  symbol:   method readFromNBT(NBTTagCompound)
  location: variable tileentity of type TileEntity
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:1247: error: cannot find symbol
                                if (this.field_147308_k && this.client.player.getStatFileWriter().getValue(statbase) == 0) {
                                                                             ^
  symbol:   method getStatFileWriter()
  location: variable player of type EntityPlayerSP
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:1260: error: cannot find symbol
                        this.client.player.getStatFileWriter().setValue(this.client.player, statbase, i);
                                          ^
  symbol:   method getStatFileWriter()
  location: variable player of type EntityPlayerSP
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:1598: error: cannot find symbol
                        scoreobjective.func_96681_a(packetIn.getObjectiveValue());
                                                            ^
  symbol:   method getObjectiveValue()
  location: variable packetIn of type SPacketScoreboardObjective
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/network/NetHandlerPlayClient.java:1606: error: cannot find symbol
                                scoreobjective1.func_96681_a(packetIn.getObjectiveValue());
                                                                     ^
  symbol:   method getObjectiveValue()
  location: variable packetIn of type SPacketScoreboardObjective
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/gui/GuiIngameMenu.java:76: error: cannot find symbol
                        this.mc.displayGuiScreen(new GuiAchievements(this, this.mc.player.getStatFileWriter()));
                                                                                         ^
  symbol:   method getStatFileWriter()
  location: variable player of type EntityPlayerSP
/home/wds/Dev/wdl/1.09/build/sources/main/java/net/minecraft/client/gui/GuiIngameMenu.java:79: error: cannot find symbol
                        this.mc.displayGuiScreen(new GuiStats(this, this.mc.player.getStatFileWriter()));
                                                                                  ^
  symbol:   method getStatFileWriter()
  location: variable player of type EntityPlayerSP
18 errors
:1.09:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':1.09:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 29 mins 31.985 secs
----------------------------------------
Compilation failed.
If this was due to a bad class file, try running "gradlew setupDecompWorkspace"
The cause of this behavior is being investigated.

**Comment by Pokechu22** [comment]
Your patched base source is out-of-date in comparison to the mappings (e.g. `isEntityAlive` should be `isAlive` now).  Running `gradlew applyBasePatches` should fix it, but that's supposed to happen automatically when you run `build`...

**Comment by Tsoccerguy3** [comment]
I did the
 gradlew applyBasePatches
gradlew setupdecompworkspace
gradlew build

Still failed to compile on commandline 


C:\Users\ASUS\Dev\wdl>gradlew build

> Configure project :1.09-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.09.4-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.10-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.10.2-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.11-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.11.2-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.12-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.12.1-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Configure project :1.12.2-litemod
This mapping 'snapshot_20180925' was designed for MC 1.13! Use at your own peril.

> Task :1.09:processBasePatches
Generating patch for net.minecraft.client.gui.GuiIngameMenu from C:\Users\ASUS\Dev\wdl\1.09\src\main\base\net\minecraft\client\gui\GuiIngameMenu.java to C:\Users\ASUS\Dev\wdl\1.09\src\main\base-patches\net.minecraft.client.gui.GuiIngameMenu.patch
Generating patch for net.minecraft.client.multiplayer.WorldClient from C:\Users\ASUS\Dev\wdl\1.09\src\main\base\net\minecraft\client\multiplayer\WorldClient.java to C:\Users\ASUS\Dev\wdl\1.09\src\main\base-patches\net.minecraft.client.multiplayer.WorldClient.patch
Generating patch for net.minecraft.client.network.NetHandlerPlayClient from C:\Users\ASUS\Dev\wdl\1.09\src\main\base\net\minecraft\client\network\NetHandlerPlayClient.java to C:\Users\ASUS\Dev\wdl\1.09\src\main\base-patches\net.minecraft.client.network.NetHandlerPlayClient.patch
Generating patch for net.minecraft.inventory.InventoryBasic from C:\Users\ASUS\Dev\wdl\1.09\src\main\base\net\minecraft\inventory\InventoryBasic.java to C:\Users\ASUS\Dev\wdl\1.09\src\main\base-patches\net.minecraft.inventory.InventoryBasic.patch
Generating patch for net.minecraft.crash.CrashReport from C:\Users\ASUS\Dev\wdl\1.09\src\main\base\net\minecraft\crash\CrashReport.java to C:\Users\ASUS\Dev\wdl\1.09\src\main\base-patches\net.minecraft.crash.CrashReport.patch
Generating patch for net.minecraft.client.ClientBrandRetriever from C:\Users\ASUS\Dev\wdl\1.09\src\main\base\net\minecraft\client\ClientBrandRetriever.java to C:\Users\ASUS\Dev\wdl\1.09\src\main\base-patches\net.minecraft.client.ClientBrandRetriever.patch
Generating patch for net.minecraft.client.resources.DefaultResourcePack from C:\Users\ASUS\Dev\wdl\1.09\src\main\base\net\minecraft\client\resources\DefaultResourcePack.java to C:\Users\ASUS\Dev\wdl\1.09\src\main\base-patches\net.minecraft.client.resources.DefaultResourcePack.patch

> Task :1.09:compileJava FAILED
C:\Users\ASUS\Dev\wdl\1.09\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:926: error: cannot find symbol
                        this.world = new WorldClient(this, new WorldSettings(0L, packetIn.getGameType(), false, this.client.world.getWorldInfo().isHardcoreModeEnabled(), packetIn.getWorldType()), packetIn.getDimensionID(), packetIn.getDifficulty(), this.client.profiler);
                                                                                                                                                ^
  symbol:   method isHardcoreModeEnabled()
  location: class WorldInfo
C:\Users\ASUS\Dev\wdl\1.09\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1401: error: cannot find symbol
                entityplayer.capabilities.isFlying = packetIn.isFlying();
                            ^
  symbol:   variable capabilities
  location: variable entityplayer of type EntityPlayer
C:\Users\ASUS\Dev\wdl\1.09\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1402: error: cannot find symbol
                entityplayer.capabilities.isCreativeMode = packetIn.isCreativeMode();
                            ^
  symbol:   variable capabilities
  location: variable entityplayer of type EntityPlayer
C:\Users\ASUS\Dev\wdl\1.09\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1403: error: cannot find symbol
                entityplayer.capabilities.disableDamage = packetIn.isInvulnerable();
                            ^
  symbol:   variable capabilities
  location: variable entityplayer of type EntityPlayer
C:\Users\ASUS\Dev\wdl\1.09\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1404: error: cannot find symbol
                entityplayer.capabilities.allowFlying = packetIn.isAllowFlying();
                            ^
  symbol:   variable capabilities
  location: variable entityplayer of type EntityPlayer
C:\Users\ASUS\Dev\wdl\1.09\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1405: error: cannot find symbol
                entityplayer.capabilities.func_75092_a(packetIn.getFlySpeed());
                            ^
  symbol:   variable capabilities
  location: variable entityplayer of type EntityPlayer
C:\Users\ASUS\Dev\wdl\1.09\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1406: error: cannot find symbol
                entityplayer.capabilities.setWalkSpeed(packetIn.getWalkSpeed());
                            ^
  symbol:   variable capabilities
  location: variable entityplayer of type EntityPlayer
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':1.09:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
9 actionable tasks: 5 executed, 4 up-to-date
----------------------------------------
Compilation failed.
If this was due to a bad class file, try running "gradlew setupDecompWorkspace"
The cause of this behavior is being investigated.

**Comment by Pokechu22** [comment]
Hm, maybe try running `clean build`?  This is super weird though...

**Comment by Tsoccerguy3** [comment]
tried gradlew clean build
clean build
git clean
git clean build
and some other cmds that don't exit

Tried again after updating , git for windows and gradle . you must have set something in eclipse that is not availiable from the commandline . It fails in Win 10 x64 and Mint 19 Cinnamon . i can compile the 1.12.2 and 1.12 litemods individually .

**Comment by Pokechu22** [comment]
Sorry for the delay.  I _think_ that I actually have ran into this myself, and that it might be a gradle bug related to incremental compilation, but I've got no way of consistently reproducing it.  If possible, can you do `./gradlew build --debug | tee debug.log` and then send me the debug.log?  Debug level includes info about what it's compiled before and what it's compiling again, so that'd help confirm whether or not that's the cause.

**Comment by Tsoccerguy3** [comment]
I left a PM on the Minecraft forums with link to log

**Comment by Tsoccerguy3** [comment]
New log posted , link in Minecraft forum
crash a first incremental patch

**Comment by Pokechu22** [comment]
This should be fixed on the BEGradle end of things; download and install the newest build of that.

The mistake was that during `build` (&rArr; `processBasePatches`), it always generates patches, instead of applying them.  If the mappings version changed, or the patches themselves changed (e.g. to accommodate a newer mappings version), it'd overwrite the patches with the old version instead of applying the new one.  I've changed it to check for which version was modified more recently (and also to check for whether the jar was modified) and apply patches in that case.

Since it already generated patches based on the incorrect version, you'll probably need to `git reset --hard` beforehand to undo that (this will also undo any other changes you have made locally but not commited, though).

**Comment by Tsoccerguy3** [comment]
After a Git reset on both WDL and Gradle-extensions , the build completed
, any reason 1.13 and 1.13.1 were left out of settings.gradle ?

**Comment by Pokechu22** [comment]
I don't have a reproducible build setup for 1.13 or 1.13.1 yet.  (I hacked together an SRG and the patches, but they're not stable and not ready for general use).  I'm currently working on setting up FG 3, at which point they'll all work.  Basically, they're not included because as-is there's no way for me to get it to compile on other machines.

**Comment by Tsoccerguy3** [comment]
fixed
